# Generated by Django 4.2.16 on 2025-05-25 18:19

from django.db import migrations, models
import my_website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('intro_text', models.TextField(blank=True, help_text='Intro or lead paragraph')),
                ('at_a_glance', models.TextField(blank=True, help_text="Short summary or 'At a Glance' section")),
                ('headshot', models.ImageField(blank=True, null=True, upload_to='headshots/')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(help_text='Upload a PDF or Word document (.pdf, .doc, .docx)', upload_to='resumes/', validators=[my_website.models.validate_resume_file_extension])),
                ('description', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
            ],
        ),
    ]
