# Generated by Django 4.2.16 on 2025-05-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopage',
            name='my_resume_header',
            field=models.TextField(blank=True, help_text='word choice for Resume Section header'),
        ),
    ]
