# Generated by Django 4.2.16 on 2025-09-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0002_portfoliopage_my_resume_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Hayden Bussard', help_text='The title that appears in the browser tab.', max_length=100)),
                ('headshot', models.ImageField(blank=True, help_text='The main circular profile photo displayed on the home page.', null=True, upload_to='headshots/')),
                ('lead_paragraph', models.CharField(default='Welcome to my personal website!', help_text='The main welcoming sentence under the headshot.', max_length=255)),
                ('card_title_professional', models.CharField(default='Professional Profile', help_text='Title for the primary call-to-action card.', max_length=100)),
                ('card_text_professional', models.TextField(default='Learn about my background and explore my professional experiences.', help_text='Text content inside the primary call-to-action card.')),
                ('footer_text', models.TextField(default="This website was developed using Django (a Python web framework), Bootstrap for responsive design, and it's hosted on Heroku, allowing for easy scaling and management.", help_text='The small paragraph at the bottom describing the tech stack.')),
                ('website_info_link_text', models.CharField(default='To learn more about how this site was built, click here.', help_text="The entire text for the small link below the footer text. Use '$$$' where the link should go.", max_length=255)),
            ],
            options={
                'verbose_name': 'Home Page Content',
                'verbose_name_plural': 'Home Page Content',
            },
        ),
    ]
