# Generated by Django 4.2.16 on 2025-09-29 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0003_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title for this skills section (e.g., Technical Skills, Soft Skills).', max_length=100, unique=True)),
                ('order', models.IntegerField(default=0, help_text='The order in which categories should appear on the page (lower number means earlier).')),
            ],
            options={
                'verbose_name': 'Skill Category',
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The text for the skill item (e.g., Technical Problem Solving).', max_length=255)),
                ('note', models.CharField(blank=True, help_text='Optional note/clarification for the skill (e.g., I have not renewed that certificate).', max_length=500, null=True)),
                ('order', models.IntegerField(default=0, help_text='The order in which skills should appear within their category.')),
                ('category', models.ForeignKey(help_text='The category this skill belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='my_website.skillcategory')),
            ],
            options={
                'verbose_name': 'Skill Item',
                'verbose_name_plural': 'Skill Items',
                'ordering': ['order', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
    ]
