# Generated by Django 4.2.16 on 2025-09-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0004_skillcategory_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_header', models.CharField(default='My Skills', help_text="The main heading for the page (e.g., 'My Skills', 'Skillset Breakdown').", max_length=200)),
                ('intro_text', models.TextField(blank=True, help_text='Optional introductory text for the skills page.', null=True)),
            ],
            options={
                'verbose_name': 'Skills Page Content (Singleton)',
                'verbose_name_plural': 'Skills Page Content (Singleton)',
            },
        ),
    ]
