# Generated by Django 4.2.16 on 2025-09-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0005_skillspagecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillspagecontent',
            name='main_header',
            field=models.CharField(blank=True, default='My Skills', help_text="The main heading for the page (e.g., 'My Skills', 'Skillset Breakdown'). Leave blank to display no main header.", max_length=200, null=True),
        ),
    ]
