# Generated by Django 4.2.16 on 2025-09-29 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0006_alter_skillspagecontent_main_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeyondWorkPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_header', models.CharField(blank=True, default='Beyond Work: Who I Am', help_text='The main H1 heading for the page. Leave blank to display no main header.', max_length=200, null=True)),
                ('browser_title', models.CharField(default='Beyond Work', help_text='The title that appears in the browser tab.', max_length=100)),
            ],
            options={
                'verbose_name': 'Beyond Work Page Content (Singleton)',
                'verbose_name_plural': 'Beyond Work Page Content (Singleton)',
            },
        ),
        migrations.CreateModel(
            name='BeyondWorkSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="The heading for this section (e.g., 'Lifelong Learner', 'Very Active').", max_length=100)),
                ('intro_paragraph', models.TextField(blank=True, help_text='The main paragraph text that appears immediately under the section title.', null=True)),
                ('order', models.IntegerField(default=0, help_text='The order in which sections should appear (lower number means earlier).')),
            ],
            options={
                'verbose_name': 'Beyond Work Section',
                'verbose_name_plural': 'Beyond Work Sections',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SectionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The text content for this detail.')),
                ('detail_type', models.CharField(choices=[('LI', 'List Item (Bullet Point)'), ('P', 'Paragraph')], default='LI', help_text="Select 'List Item' for a bullet point, or 'Paragraph' for extra text.", max_length=2)),
                ('order', models.IntegerField(default=0, help_text='The order in which details should appear within their section.')),
                ('section', models.ForeignKey(help_text='The section this detail belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='my_website.beyondworksection')),
            ],
            options={
                'verbose_name': 'Section Detail',
                'verbose_name_plural': 'Section Details',
                'ordering': ['order'],
            },
        ),
    ]
